CREATE TABLE T_USER_COMMENTS(
COMMENT_ID NUMBER(9,0),
COMMENT VARCHAR2(300) NOT NULL,
COMMENT_ON TIMESTAMP(2) NOT NULL,
EMPLOYEE_ID NUMBER(9,0) NOT NULL
CONSTRAINT PK_USER_COMMENTS PRIMARY KEY (COMMENT_ID),
CONSTRAINT FK_USER_COMMENTS FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE_DETAIL (EMPLOYEE_ID))
;

CREATE SEQUENCE S_USER_COMMENTS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 NOCYCLE NOCACHE ORDER;

COMMIT;