CREATE TABLE T_EMPLOYEE_PRJ_REF(
EMP_PRJ_REF_ID NUMBER(9,0),
EMPLOYEE_ID NUMBER(9,0),
PROJECT_ID NUMBER(9,0),
CONSTRAINT PK_EMPLOYEE_PRJ_REF PRIMARY KEY (EMP_PRJ_REF_ID),
CONSTRAINT FK_EMPLOYEE_PRJ_REF_1 FOREIGN KEY (PROJECT_ID) REFERENCES T_PROJECT_DETAILS (PROJECT_ID),
CONSTRAINT FK_EMPLOYEE_PRJ_REF_2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE_DETAIL (EMPLOYEE_ID))
;

CREATE SEQUENCE S_EMPLOYEE_PRJ_REF INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 NOCYCLE NOCACHE ORDER;

ALTER TABLE T_EMPLOYEE_DETAIL DROP COLUMN PROJECT_ID; 
ALTER TABLE T_EMPLOYEE_DETAIL ADD EMP_ROLE VARCHAR2(200); 

COMMIT;