DROP TABLE T_ONBOARDING_PROGRESS;
DROP INDEX S_ONBOARDING_PROGRESS;

DROP TABLE T_ONBOARDING_PROCESS;
DROP INDEX S_ONBOARDING_PROCESS;

DROP TABLE T_EMPLOYEE_DETAIL;
DROP INDEX S_EMPLOYEE_DETAIL;

DROP TABLE T_PROJECT_DETAILS;
DROP INDEX S_PROJECT_DETAILS;

COMMIT;
    