CREATE TABLE T_USER_COMMENTS (
COMMENT_ID NUMBER(9,0), 
COMMENT_DETAILS VARCHAR2(300) NOT NULL, 
COMMENT_TIME TIMESTAMP NOT NULL, 
EMPLOYEE_ID NUMBER(9,0) NOT NULL,
PROCESS_ID NUMBER(9,0),
PROGRESS_ID NUMBER(9,0),
CONSTRAINT PK_USER_COMMENTS PRIMARY KEY (COMMENT_ID),
CONSTRAINT FK_USER_COMMENTS FOREIGN KEY (EMPLOYEE_ID) REFERENCES T_EMPLOYEE_DETAIL (EMPLOYEE_ID),
CONSTRAINT FK_USER_COMMENTS_1 FOREIGN KEY (PROCESS_ID) REFERENCES T_ONBOARDING_PROCESS (PROCESS_ID),
CONSTRAINT FK_USER_COMMENTS_2 FOREIGN KEY (PROGRESS_ID) REFERENCES T_ONBOARDING_PROGRESS (PROGRESS_ID));

CREATE SEQUENCE S_USER_COMMENTS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 NOCYCLE NOCACHE ORDER;

COMMIT;
